### PR TITLE
Fix glitches when a single UUID joins via multiple connections

### LINKED ISSUE #54: [Bug]: Error dispatching event ChatEvent
#### Issue Description: 

Sometimes a user lose the cooperation with the bungeechat and the chatstyle is like vanilla minecraft. I think this fail come from bungeechat and not from bungee. And I get a error in the bungeecord log.

I will update whis report with more informations if I get more.

#### Steps to reproduce:

1. Join to the server.
2. Disconnect your internet.
3. Wait 18 sec.
4. Connect your internet.
5. You lose the server connection. Rejoin and you see a error in the bungeecord log and if you write you do not get your prefix like your bungeechat configuration.

(6.) After a new normal rejoin the prefix is correct and you do net get more errors.

Test with "RedstoneFuture":

____
#### Affected Versions: 

- Minecraft: 1.12.2
- BungeeChat:  2.1.6.855

#### Your most recent log or stack trace file where the issue was present: 

stack tree on bungeecord:

https://pastebin.com/gP9vZWQM

### PR DESCRIPTION
**Pull request by MrVoltz**
BungeeChat join/leave/switch events now fire only for the first connection.

Fixes #54

### CODE REVIEW

File: src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java [hunk 1]
```diff
@@ -1,11 +1,12 @@
...
 
+import com.google.common.collect.MapMaker;
 import dev.aura.bungeechat.event.BungeeChatJoinEvent;
 import dev.aura.bungeechat.event.BungeeChatLeaveEvent;
 import dev.aura.bungeechat.event.BungeeChatServerSwitchEvent;
-import java.util.LinkedList;
-import java.util.List;
-import java.util.UUID;
+
+import java.util.*;
```
Comment (BrainStone) [inline src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java:8]: Please run `./gradlew spotlessApply` this will only explicitly import stuff that’s needed.  
No wildcard imports!

File: src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java [hunk 2]
```diff
@@ -16,33 +17,31 @@
 import net.md_5.bungee.event.EventPriority;
 
 public class BungeeChatEventsListener implements Listener {
-  private static final List<UUID> joinedPlayers = new LinkedList<>();
-  private static final List<UUID> duplicatePlayers = new LinkedList<>();
-
-  @EventHandler(priority = EventPriority.HIGHEST)
-  public void onPlayerJoin(PostLoginEvent e) {
```
Comment (BrainStone) [inline src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java:23]: Why did you remove the player join event?

Note im currently on mobile so only pointing out the glaringly obvious things. I might have missed a thing or two.

**Review by BrainStone — CHANGES_REQUESTED** [review]
Will take a closer look later. 

But I like that you added a unit test! Very much appreciated :)

File: src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java (hunk 1 above)
Comment (MrVoltz) [reply src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java:7]: I've run it and updated this PR.

File: src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java (hunk 2 above)
Comment (MrVoltz) [reply src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java:23]: `PostLoginEvent` was used only to check for duplicate connections. I've moved this check to `ServerSwitchEvent`. `BungeeChatJoinEvent` was and still is called from `ServerSwitchEvent`.

**Review by BrainStone — APPROVED** [review]
There were some things I didn't quite like about your PR. But all were minor or just a question of code style. So I went ahead and fixed it.  
I explained what I changed and why in the respective commits.

If you're happy with my changes, I will merge it, as I'm happy with the code overall.  
Generally speaking I really like the way you solved the underlying issue. Makes a lot of sense to me.  
And lastly to be sure: You did test the changes live, right? If not please do so.

**Comment by MrVoltz** [comment]
Thank you for the review. I used MapMaker, because WeakHashMap has only weak keys. If you don't mind that the `ProxiedPlayer`s are strongly referenced, you could use a normal HashMap as well.

Yes, I am using the original code from the PR on our server. With this new code it can happen that a player is on the server, but not registered to BungeeChat (thus can't send any messages). I am OK with it, because it happened just once and it affects only the single player, not the entire network (before this fix nobody on the network could chat when that happened).

The proper solution would probably be to keep some sort of queue for the connections and when the primary one disconnects, set the next one in order as primary and call BungeeChatJoinEvent on it.

**Comment by BrainStone** [comment]
> I used MapMaker, because WeakHashMap has only weak keys. If you don't mind that the `ProxiedPlayer`s are strongly referenced, you could use a normal HashMap as well.

I see. I'll look for a map with weak keys that's not a concurrent map.

> With this new code it can happen that a player is on the server, but not registered to BungeeChat (thus can't send any messages).

Can you elaborate how? Is this related to the me using `WeakHashMap` or do you mean that happens with your code too and is a general flaw of your implementation?

**Comment by MrVoltz** [comment]
> Can you elaborate how? Is this related to the me using WeakHashMap or do you mean that happens with your code too and is a general flaw of your implementation?

Its a general flaw of my implementation.

```
player 1 | J-L
player 2 |  J---...
```

Assume player 1 is just a glitch and the real player is player 2. He wouldn't be able to interact with chat until he relogs. The solution would be:

```
player 1 | J-L
player 2 |  J-R--...
```

Where R is where `BungeeChatJoinEvent` would be fired for player 2.

**Comment by BrainStone** [comment]
Ah I see. No big deal then. But shouldn't switching the server fix everything?

**Comment by MrVoltz** [comment]
> But shouldn't switching the server fix everything?

You are right, it should.

**Comment by BrainStone** [comment]
Do not worry about the failed checks. Those are (more or less) on me. I'll change the map implementation to something fitting and then I'll merge it.
